visitorMessagesManager.add({id : 'v_0001', shapeCode : 1, colorCode : 1, text : 'No.1 is me'});
visitorMessagesManager.add({id : 'v_0002', shapeCode : 2, colorCode : 2, text : '二番じゃだめなんですか？'});
visitorMessagesManager.add({id : 'v_0003', shapeCode : 3, colorCode : 4, text : '三枚目登場'});
visitorMessagesManager.add({id : 'v_0004', shapeCode : 4, colorCode : 8, text : '四露死苦'});
visitorMessagesManager.add({id : 'v_0005', shapeCode : 5, colorCode : 10, text : '五臓'});
visitorMessagesManager.add({id : 'v_0006', shapeCode : 5, colorCode : 12, text : '六腑'});
visitorMessagesManager.add({id : 'v_0007', shapeCode : 3, colorCode : 11, text : 'なななななななななななななななななななn'});
visitorMessagesManager.add({id : 'v_0008', shapeCode : 2, colorCode : 9, text : '八方美人で何が悪い'});

visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 8, y : -9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -7, y : 8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : 1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -1, y : 10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : 9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 1, y : -10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -9, y : 7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 5, y : -4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 6, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 4, y : -7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -7, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -1, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -9, y : -5}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -4, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -7, y : 9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : -2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -4, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 8, y : -8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : 6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : 9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 5, y : -1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : -2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : 8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : -8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -5, y : -4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 10, y : 5}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -3, y : 4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -4, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : -2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -9, y : 9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : 10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 10, y : -8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : -10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 4, y : -8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 6, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 2, y : 8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -5, y : -9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 9, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -9, y : -10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 4, y : -4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -7, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -5, y : -1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 6, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 9, y : 1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -10, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : 7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 4, y : 10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 3, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -7, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 1, y : 7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 1, y : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 4, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -1, y : 9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -8, y : 6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 0, y : -7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -10, y : -8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -1, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -3, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : 10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : -4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : 8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -3, y : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : 7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -1, y : 5}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 0, y : -1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -10, y : -1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 9, y : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 10, y : -10}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -2, y : 8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -5, y : 0}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 6, y : 7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 9, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -10, y : -5}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 1, y : -9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 0, y : -4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : 9}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 1, y : -3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 3, y : 8}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 6, y : 3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -6, y : 3}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 8, y : -4}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 1, y : -1}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : -7, y : -6}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 2, y : -7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 2, y : 7}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 7, y : -2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0001", o : { type : COMMAND_MOVE, x : 10, y : 0}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 0, y : 6}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -8, y : 6}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 4, y : 6}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 8, y : -4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -2, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 0, y : 1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -4, y : 7}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : -10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 3, y : 7}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -2, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -8, y : -9}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 10, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 0, y : -8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -4, y : 9}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -10, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -8, y : 1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 6, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -9, y : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 5, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -5, y : -10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -8, y : 6}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -7, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 9, y : 5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -2, y : -3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 1, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : -8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 10, y : 0}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -4, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -5, y : -2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -10, y : 5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 0, y : 4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 3, y : 4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 6, y : -7}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : -7}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 2, y : -9}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 9, y : -2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -6, y : 5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : 5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 4, y : 8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : -10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : 4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 9, y : -4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : 5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 0, y : -6}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -6, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -6, y : 4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 2, y : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : 6}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -9, y : -3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 3, y : 9}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 7, y : 1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 4, y : -3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 10, y : 9}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -5, y : 1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 4, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -9, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 2, y : 5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : 8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -6, y : 8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 10, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 3, y : -7}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 5, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 0, y : 0}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 8, y : 3}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 10, y : -4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -5, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 8, y : -1}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -7, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : 8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -7, y : 9}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -2, y : 4}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : -8}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -3, y : -5}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : -1, y : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 2, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 4, y : -7}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 3, y : 10}});
visitorMessagesManager.control({ id : "v_0002", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : 8}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -5, y : -1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -7, y : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 8, y : -4}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -2, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 6, y : 6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 3, y : -7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -8, y : 10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -3, y : 6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -8, y : -5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -10, y : 7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 0, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -10, y : -7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -7, y : 1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 0, y : -10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : -9}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : -3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 6, y : -1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -5, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -4, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 8, y : 8}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 2, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 6, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 8, y : 10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 0, y : 7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -4, y : -6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -1, y : 10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -6, y : 6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 8, y : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -1, y : -10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -7, y : 3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -1, y : -1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 10, y : -7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -3, y : -10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : 10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -5, y : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : -4}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 2, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -4, y : -10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 0, y : 6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 2, y : 6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -5, y : 3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : -3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 10, y : -1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 5, y : -3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -8, y : -6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 8, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 4, y : -4}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -1, y : -1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -3, y : -7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : 0}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -6, y : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 7, y : 3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 3, y : 3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -2, y : 1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -7, y : -7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -8, y : -6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -2, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 3, y : 0}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 10, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : -5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -2, y : 4}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 2, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 10, y : -6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 5, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 9, y : -9}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 4, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -7, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 5, y : -8}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -7, y : 5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 8, y : -9}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 3, y : -6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 3, y : -5}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 0, y : 7}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 4, y : 1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -5, y : -9}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 7, y : 10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 0, y : -8}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 6, y : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 4, y : -2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 5, y : 10}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 2, y : 6}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 10, y : 9}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : 3, y : -3}});
visitorMessagesManager.control({ id : "v_0003", o : { type : COMMAND_MOVE, x : -10, y : 8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -8, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : -1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -3, y : -3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -7, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 9, y : -5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : -1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 10, y : 1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -4, y : -6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -4, y : -1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : -10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -9, y : -10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : -4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 5, y : -10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : -2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 2, y : -8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -9, y : -2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : -7}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -1, y : 7}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 8, y : -4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 5, y : -2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : 8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -5, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 8, y : -10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -9, y : -5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -3, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : -9}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : 4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : -7}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -6, y : -3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : 10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 4, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -4, y : 3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 5, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : 8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : -4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 10, y : -1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : -5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 7, y : -10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : 10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 4, y : 4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -4, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -1, y : 10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : 8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : -9}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 5, y : 10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 9, y : 3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : -3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -7, y : 10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -1, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : -8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -1, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 7, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -1, y : -4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -2, y : -7}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : 3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -9, y : 10}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 2, y : 6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -5, y : 8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : 9}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 5, y : 1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 6, y : 1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -1, y : -2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -10, y : -3}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : -2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 0, y : 1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -4, y : 0}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 3, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 8, y : -9}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 9, y : -9}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -5, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -9, y : -8}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 7, y : -1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -4, y : -9}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 8, y : -2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 10, y : 1}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 1, y : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 9, y : 4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 7, y : 5}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 8, y : -6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -7, y : 0}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 1, y : 4}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : -6, y : 7}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 4, y : -6}});
visitorMessagesManager.control({ id : "v_0004", o : { type : COMMAND_MOVE, x : 8, y : 5}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : 3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -1, y : 9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 3, y : -9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 5, y : -6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -1, y : -1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : -4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -9, y : -3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -8, y : 7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -10, y : 4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : -9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 7, y : -7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -6, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -5, y : 5}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 5, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : -8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 0, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 0, y : -8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -8, y : -2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -7, y : -4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -1, y : -10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : -3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -2, y : 9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 1, y : 3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 5, y : 8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -2, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 2, y : -6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 10, y : 10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 5, y : -10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -7, y : 7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 10, y : -4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : -2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 5, y : 7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : -6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -2, y : 6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -8, y : -8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 8, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -1, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -6, y : -8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -6, y : -3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 10, y : 4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 6, y : -9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -7, y : 0}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -9, y : -5}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 10, y : -8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -10, y : -1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -8, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : 4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -6, y : 4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : -6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 6, y : 6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : 10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 1, y : -9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -1, y : -7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : -2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 0, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : -4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 3, y : 8}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -4, y : 5}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -7, y : -6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 0, y : -3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 2, y : -3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -6, y : -9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 1, y : 4}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -4, y : -6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 2, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -5, y : -2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -3, y : 3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 7, y : -7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 2, y : -1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 7, y : 0}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -10, y : 5}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 8, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : -1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 5, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -8, y : -5}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 1, y : 7}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -2, y : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -6, y : -9}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 4, y : 3}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 0, y : 10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -5, y : 6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -4, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 2, y : 6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -2, y : 6}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 9, y : -10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -7, y : 10}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : -3, y : 0}});
visitorMessagesManager.control({ id : "v_0005", o : { type : COMMAND_MOVE, x : 10, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -7, y : -6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -1, y : -1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : 3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : -6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 0, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 3, y : -3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -10, y : 10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 5, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : 8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -8, y : 3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -7, y : 0}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 6, y : -8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -8, y : -9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 6, y : 0}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 8, y : 5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 8, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -3, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : 5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -7, y : 9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 3, y : -6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : -7}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 8, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -9, y : -1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : 9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : -7}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : -3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -3, y : 8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 5, y : 10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 2, y : 8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : -4}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -9, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 5, y : -3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : -10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -3, y : -1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : 9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : 8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -7, y : 9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -2, y : 9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 3, y : 0}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 7, y : -8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -3, y : -10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 9, y : 10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 0, y : -9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : 8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : -8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : -7}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -6, y : 6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -6, y : -3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -2, y : 10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 9, y : -3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -1, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -3, y : 6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : 6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 6, y : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -6, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : 3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 6, y : -4}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -2, y : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -2, y : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 0, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : 4}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : -10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 5, y : 0}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -2, y : 5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -10, y : 5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : -9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -10, y : -4}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -10, y : 0}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 5, y : 8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : 3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -1, y : -5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 5, y : 10}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -8, y : -7}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : 0}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -6, y : 3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -7, y : 9}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -4, y : 6}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 2, y : -2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 2, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : -7}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : -5, y : -3}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 4, y : 5}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 4, y : 1}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 10, y : 4}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 1, y : -8}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0006", o : { type : COMMAND_MOVE, x : 7, y : -2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 9, y : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 3, y : 10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 7, y : -7}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : 9}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 7, y : -8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 4, y : 3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 6, y : 8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 7, y : 0}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -10, y : 1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 8, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : 10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 8, y : 5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -3, y : -8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 8, y : -5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -8, y : -7}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -9, y : -7}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 9, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 7, y : 9}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 2, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -9, y : 4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 2, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 2, y : -2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 6, y : 10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -2, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 9, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 5, y : -9}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 9, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 2, y : -5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 9, y : -9}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 0, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 8, y : 7}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -4, y : 6}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 6, y : 5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : 0}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -8, y : 4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -1, y : 6}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : 8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 3, y : 8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -8, y : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 3, y : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -7, y : 1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -1, y : 1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -1, y : 3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 7, y : -6}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -6, y : 7}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 3, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -7, y : -8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -10, y : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 4, y : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -2, y : 0}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -8, y : 8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -1, y : -6}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -2, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 0, y : 7}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -9, y : 4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : -4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -4, y : 1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 2, y : 8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : 5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : -4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 8, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : 9}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : 9}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : -4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 3, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -9, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : 0}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 1, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -3, y : 3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : 8}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -5, y : -3}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -10, y : 5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -2, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 10, y : -1}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 4, y : 0}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -6, y : -4}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 9, y : -6}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -4, y : -10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 0, y : -6}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : 7, y : 10}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -4, y : 5}});
visitorMessagesManager.control({ id : "v_0007", o : { type : COMMAND_MOVE, x : -7, y : -7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -8, y : -4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 1, y : 8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -7, y : -5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -10, y : -7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -4, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 2, y : 6}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -10, y : 6}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 2, y : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -3, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : 10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 0, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 10, y : 9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -1, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -6, y : -10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -8, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -6, y : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -7, y : 5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -5, y : 9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 1, y : -9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 1, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -3, y : -1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -7, y : -7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -9, y : 4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 10, y : -5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 0, y : 9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : -10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -1, y : -4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -3, y : 3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 1, y : 1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -2, y : -2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 4, y : 9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -6, y : -9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -9, y : 7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : 1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 0, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 10, y : 0}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 8, y : -4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -4, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -2, y : 10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 2, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 4, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 1, y : 10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -2, y : -7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -9, y : 4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -4, y : 10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 2, y : 5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 0, y : 0}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -9, y : 4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -10, y : 1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 1, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 4, y : 7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 6, y : 0}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -4, y : 4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : -9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 5, y : 8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : 4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 9, y : -5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -10, y : 5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -7, y : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -4, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -1, y : 9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 8, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -6, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 4, y : 8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -2, y : 8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : -1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -10, y : 6}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 3, y : -1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -7, y : 0}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -3, y : 3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -2, y : -2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 8, y : 5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -4, y : -9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 6, y : -6}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -7, y : -1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -8, y : -1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 8, y : 7}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 9, y : 3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 2, y : 5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 8, y : -8}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 10, y : -9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -9, y : -1}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -5, y : -3}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -10, y : 0}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 9, y : -10}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_RESIZE, size : 2}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 4, y : 9}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -5, y : 4}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : 2, y : 6}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -8, y : 5}});
visitorMessagesManager.control({ id : "v_0008", o : { type : COMMAND_MOVE, x : -2, y : 0}});